print("Hello, World!")
print("This is a test script for Git.")
print("Let's see how Git tracks changes.")
print("Adding some more lines to test version control.")
print("simply a test")
print("This is a sample Python script for testing Git.")
